@host = http://localhost:8080/api 


###
# @name login
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
	"username": "IN-00015",
	"password": "1234"
}

###

@authToken = {{login.response.body.data.auth_token}}

###
POST {{host}}/user HTTP/1.1
content-type: application/json

{
	"name": "Deeya",
	"pass": "1234",
	"ref_dist_id": "IN-00006",
	"ref_center_code": "003",
	"place": "right"
}

###
GET {{host}}/user/tree/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}

###
POST {{host}}/order/IN-00015 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"products": [
		{
		"product_id": 1
		},
		{
		"product_id": 2
		},
		{
		"product_id": 3
		}
	],
	"coupons": [
		{
		"v_id": "A86E4A7AA7"
		},
		{
		"v_id": "BF8CC60240"
		}
	],
	"total_amount": 1210.0
}
