@host = http://localhost:8080/api 


###
# @name login
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
	"username": "IN-00013",
	"password": "1234"
}

###

@authToken = {{login.response.body.data.auth_token}}	

###
POST {{host}}/user HTTP/1.1
content-type: application/json

{
	"name": "Deeya",
	"pass": "1234",
	"ref_dist_id": "IN-00006",
	"ref_center_code": "003",
	"place": "right"
}

###
GET {{host}}/user/tree/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET  {{host}}/product/orderDetails?distrib_id=IN-00003 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/order HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00013",
	"applied_coupons": [
		{
			"v_id": "62A009AF2C",
			"pin": "91D73A94C9",
			"amount_detected": 50
		}
	],
	"total_amount": 113999.00,
	"place_bvs": []
}

###
POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "ref_distrib_id": "IN-00001",
    "name": "Odin",
    "pass": "1234",
    "ref_placement_distrib_id": "IN-00012",
    "ref_placement_place": "002",
    "side": "left",
    "address1": "123 Main St",
    "address2": "Apt 101",
    "town_or_city": "Chennai",
    "district": "Chennai",
    "state_or_province": "TamilNadu",
    "email_address": "henry@gmail.com",
    "pin_or_zip_code": 560001,
    "country": "India",
    "home_phone_no": "080-12345678",
    "mobile_phone_no": "+91-9876543210"
}

###
GET  {{host}}/product/cartProducts/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/iCoupon/validate/IN-00003 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"v_id": "4F4B03E725",
	"pin": "20EAC76C2B"
}

###
GET  {{host}}/user/tree/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
GET  {{host}}/order/IN-00003 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/product/Admin HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"name": "Apple Watch",
	"quantity": 20,
	"product_images": [
		{
			"image": "/assets/productImages/appleWatch1.png"
		},
		{
			"image": "/assets/productImages/appleWatch2.png"
		},
		{
			"image": "/assets/productImages/appleWatch3.png"
		}
	],
	"shipment_time": "19:20+5ist",
	"price": 94000.00,
	"s_and_h": 200.00,
	"bv": 1000,
	"rsp": 25,
	"ep": 70.00,
	"product_category_id": 1
}

###
GET {{host}}/product HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/product/addToCart HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00013",
	"items": [
		{
			"product_id": 6
		},
		{
			"product_id": 7
		}
	]
}

###
GET {{host}}/user/getTrackingCenters/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
GET {{host}}/rsp/IN-00013 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
GET {{host}}/user/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json
###
POST {{host}}/enquiryType/ HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"name": [
	"Apply ID Card",
	"Bank Account Validation",
	"Commission/ GR Related Enquiry",
	"Ecard/ Evoucher Enquiry",
	"General Enquiry",
	"Grievanvces",
	"GST Enquiry",
	"KYC Submission",
	"P&P Related Issues",
	"Product Enquiry",
	"Q Account/Password/Security Q&W Enquiry",
	"QVI Enquiry",
	"Refund Request",
	"RSP Enquiry",
	"TDS Enquiry",
	"Telegraphic Transfer Enquiry",
	"Update Personal Information Enquiry"
	],
	"admin_name":"admin"
}


###
POST {{host}}/contactCenter/enquiryType HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

//both less than 4000
###
POST {{host}}/cheque/available HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00001",
	"place": "002",
	"l_tc": {
		"distrib_id": "IN-00002",
		"l_point": 500,
		"r_point": 1000,
		"bv_point": 500
	},
	"r_tc": {
		"distrib_id": "IN-00003",
		"l_point": 500,
		"r_point": 1000,
		"bv_point": 500
	}
}

//left less than 4000
###
POST {{host}}/cheque/available HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00001",
	"place": "002",
	"l_tc": {
		"distrib_id": "IN-00002",
		"l_point": 500,
		"r_point": 1000,
		"bv_point": 500
	},
	"r_tc": {
		"distrib_id": "IN-00003",
		"l_point": 500,
		"r_point": 1000,
		"bv_point": 3000
	}
}

//right less than 4000
###
POST {{host}}/cheque/available HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00001",
	"place": "002",
	"l_tc": {
		"distrib_id": "IN-00002",
		"l_point": 1000,
		"r_point": 3000,
		"bv_point": 500
	},
	"r_tc": {
		"distrib_id": "IN-00003",
		"l_point": 500,
		"r_point": 1000,
		"bv_point": 500
	}
}

//both greater than 4000
###
POST {{host}}/cheque/available HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00001",
	"place": "002",
	"l_tc": {
		"distrib_id": "IN-00002",
		"l_point": 500,
		"r_point": 3000,
		"bv_point": 500
	},
	"r_tc": {
		"distrib_id": "IN-00003",
		"l_point": 500,
		"r_point": 3000,
		"bv_point": 500
	}
}

###
POST {{host}}/cheque/takeCheque HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00001"
}