@host = http://localhost:8080/api 


###
# @name login
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
	"username": "IN-00003",
	"password": "1234"
}

###

@authToken = {{login.response.body.data.auth_token}}

###
POST {{host}}/user HTTP/1.1
content-type: application/json

{
	"name": "Deeya",
	"pass": "1234",
	"ref_dist_id": "IN-00006",
	"ref_center_code": "003",
	"place": "right"
}

###
GET {{host}}/user/tree/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET  {{host}}/product/orderDetails?distrib_id=IN-00003 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/order HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"distrib_id": "IN-00003",
	"place": "003",
	"applied_coupons": [
		{
			"v_id": "F429D99978",
			"pin": "6D5F3F603B",
			"amount_detected": 100
		},
		{
			"v_id": "742AF55C93",
			"pin": "A9B18D831F",
			"amount_detected": 100
		}
	],
	"total_amount": 113999.00
}

###
POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "ref_dist_id": "IN-00001",
    "name": "Harini",
    "pass": "1234",
    "ref_center_code": "003",
    "place": "left",
    "address1": "123 Main St",
    "address2": "Apt 101",
    "town_or_city": "Chennai",
    "district": "Chennai",
    "state_or_province": "TamilNadu",
    "email_address": "siva@gmail.com",
    "pin_or_zip_code": 560001,
    "country": "India",
    "home_phone_no": "080-12345678",
    "mobile_phone_no": "+91-9876543210"
}

###
GET  {{host}}/product/cartProducts/IN-00001 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

###
POST {{host}}/iCoupon/validate/IN-00003 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
	"v_id": "4F4B03E725",
	"pin": "20EAC76C2B"
}